### ISSUE TITLE
test problematic urap locus relations

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#611]
The excel file in the next comment shows locus relations that could not be fixed for urap.
That's also a test for #435

**Comment by urapadmin** [comment]
[Result_39.xlsx](https://github.com/urapadmin/kiosk/files/4602352/Result_39.xlsx)

**Comment by urapadmin** [comment]
[Result_khpp.xlsx](https://github.com/urapadmin/kiosk/files/4602618/Result_khpp.xlsx)

**Comment by lbestock** [comment]
Down to 8. Six of these are ones I can't see because of #986 (which is entirely FA-003, which is a polyamorous locus in the extreme). But I do not know why the other two are still there since I thought I had fixed all the others. There was one in the original excel file that confused me: EC-002 to EC-004. In FM that looked to me like it was proper in both places (cut by/cuts) so I didn't know what to do with it. Can you tell me which ones are broken still? And what is up with EC-002 - EC-004?

**Comment by lbestock** [comment]
Fills/is filled by might have continued to cause problems? I had fixed a broken relationship on that front but did not go into the valuelists until after synchronization; I discovered that "is filled by" was missing on the relations list, and "is filled by=fills" in the opposites list, though "fills=is filled by" was there. The relation in question was FI-031 to FI-030.

**Comment by urapadmin** [comment]
#986 should be fixed now so you can continue here.

**Comment by lbestock** [comment]
Down to two...
New ticket because it is not easy to figure out which #1094.

**Comment by lbestock** [comment]
Ah I see above that I only expected to be able to fix six because the other two are ones I don't understand. I expect them to be uid: bde6932b-7102-4630-b40b-340ebcc7df4a
and uid: 1b9c9c47-caf9-4ce1-be37-747fe1278c52
And I still won't know why.

**Comment by lbestock** [comment]
I have resolved all of these with the exception of EC-002 to EC-004, which I don't understand why it is on the list at all. The relation is in both places and is properly reciprocal (cut by/cuts through) and there are no additional relations between these two.

**Comment by urapadmin** [comment]
one day #1094 might help. But not in v1
